CREATE DATABASE IF NOT EXISTS db_pwpb_270723;

CREATE TABLE IF NOT EXISTS db_pwpb_270723.tb_menu(
  id INT(16) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  kode VARCHAR(5) UNIQUE KEY NOT NULL,
  menu VARCHAR(64) UNIQUE KEY NOT NULL,
  harga int(12) NOT NULL
);