CREATE DATABASE IF NOT EXISTS db_pwpb_260723;

CREATE TABLE IF NOT EXISTS db_pwpb_260723.tb_siswa(
  id INT(16) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  nama VARCHAR(64) UNIQUE KEY NOT NULL,
  kelas VARCHAR(16) NOT NULL
);